- name: Config all Host
  hosts: master, worker

  vars_prompt:
    - name: rke
      prompt: "What rke version? (rke1,rke2) "
      private: no
      default: "rke1"

  tasks:
    - name: Aptitude update
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - snmpd
          - chrony

    - name: Set timezone to Asia/Bangkok
      shell: timedatectl set-timezone Asia/Bangkok

    - name: Comment out the pool directive in chrony.conf
      shell: sed -i 's/pool/#pool/g' /etc/chrony/chrony.conf

    - name: Set server directive in chrony.conf
      shell: sed -i 's/#pool 2.ubuntu.#pool.ntp.org iburst maxsources 2/server clock.inet.co.th/g' /etc/chrony/chrony.conf

    - name: Restart Chrony service
      shell: systemctl restart chrony
    
    - name: Disable Swap
      shell: swapoff -a 
     
    - name: Disable Swap in fstab 
      shell: sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab

    - name: Set snmp community string
      shell: echo "rocommunity  ols-monitor " >> /etc/snmp/snmpd.conf

    - name: Restart service SNMP
      shell: systemctl restart snmpd

    - name: Install Docker
      shell: curl -s https://releases.rancher.com/install-docker/20.10.sh | sh
      when: rke == 'rke1'

    - name: Cache Docker
      copy:
        content: |
          {
            "registry-mirrors": ["https://ols-dockerhubcache.dedyn.io"]
          }
        dest: /etc/docker/daemon.json
      when: rke == 'rke1'

- name: Install nfs-common on worker
  hosts: worker
  become: yes
  tasks:
    - name: Aptitude update
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nfs-common
