- name: Config all Host
  hosts: all
  #become: yes
  #become_user: root
  tasks:
    - name: Aptitude update
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - snmpd
          - chrony

    - name: Install Docker 
      shell: curl -s https://releases.rancher.com/install-docker/20.10.sh | sh

    - name: Cache Docker
      copy:
        content: |
          {
            "registry-mirrors": ["https://ols-dockerhubcache.dedyn.io"]
          }
        dest: /etc/docker/daemon.json 

    - name: Set timezone to Asia/Bangkok
      shell: timedatectl set-timezone Asia/Bangkok

    - name: Comment out the pool directive in chrony.conf
      shell: sed -i 's/pool/#pool/g' /etc/chrony/chrony.conf

    - name: Set server directive in chrony.conf
      shell: sed -i 's/#pool 2.ubuntu.#pool.ntp.org iburst maxsources 2/server clock.inet.co.th/g' /etc/chrony/chrony.conf

    - name: Restart Chrony service
      shell: systemctl restart chrony
    
    - name: Disable Swap
      shell: swapoff -a 
     
    - name: Disable Swap in fstab 
      shell: sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab

    - name: Set snmp community string
      shell: echo "rocommunity  ols-monitor " >> /etc/snmp/snmpd.conf

    - name: Restart service SNMP
      shell: systemctl restart snmpd

- name: Rancher
  hosts: rancher-server
  become: yes
  #  become_user: root

  vars_prompt:
    - name: "ssl_option"
      prompt: "Do you want to run Rancher with SSL? (yes/no)"
      private: no
      default: "no"

  tasks: 
    - name: Deploy rancher without ssl
      shell: docker run -d --restart=unless-stopped --name rancher -p 80:80 -p 443:443 --privileged rancher/rancher:v2.6.9
      when: ssl_option == 'no'
      ignore_errors: yes

    - name: Deploy rancher with ssl
      shell: docker run -d --restart=unless-stopped --name rancher -p 80:80 -p 443:443 --privileged -v /opt/rancher:/var/lib/rancher -v /var/log/rancher/auditlog:/var/log/auditlog -v /root/rancher/ssl/cert.pem:/etc/rancher/ssl/cert.pem  -v /root/rancher/ssl/key.pem:/etc/rancher/ssl/key.pem -v /etc/localtime:/etc/localtime:ro -e AUDIT_LEVEL=1 rancher/rancher:v2.6.9 --no-cacerts
      when: ssl_option == 'yes'
      ignore_errors: yes

- name: Install nfs-common on worker
  hosts: worker
  become: yes
  tasks:
    - name: Aptitude update
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nfs-common
